rule all:
    input:
        "data/mock_data.npz"

# saved using float32
rule export_img:
    output: img="data/img.npy", plot="data/img_plot.png"
    shell: "python create_butterfly.py {output.img} {output.plot}"

# now package these together into a single .npz 
rule package:
    input:
        baselines="data/IM_Lup_baselines_and_weights.npz",
        img="data/img.npy"
    output:
        "data/mock_data.npz"
    shell:
        "python package_data.py {input.baselines} {input.img} {output}"